import { API_BASE_URL } from '../config/api';

export type DiagnosticSessionStatus = 'draft' | 'pending' | 'validated' | 'submitted' | 'reviewed';

export interface DiagnosticSessionParticipant {
  fullName?: string;
  firstName: string;
  email: string;
  whatsapp?: string;
  situation: string;
}

export interface DiagnosticSession {
  _id: string;
  status: DiagnosticSessionStatus;
  subscriptionStatus?: 'pending' | 'active';
  participant: DiagnosticSessionParticipant;
  responses: Record<string, any>;
  scores: {
    perBlock: Record<string, number>;
    total: number;
    orientation: string;
  };
  analysis?: {
    autoGenerated?: boolean;
    humanReviewed?: boolean;
    implicitStatus?: 'en_attente' | 'termine' | 'annule' | 'suspendu';
    finalOrientation?: string;
    notes?: string;
    reviewedAt?: string;
  };
  metadata?: {
    source?: string;
    userAgent?: string;
    ip?: string;
    selectedDomain?: string;
  };
  submittedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface DiagnosticSessionsFilters {
  status?: DiagnosticSessionStatus;
  search?: string;
  scoreMin?: number;
  scoreMax?: number;
  from?: string;
  to?: string;
  page?: number;
  limit?: number;
}

export interface DiagnosticSessionsResponse {
  success: boolean;
  data: DiagnosticSession[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    pages: number;
  };
}

class DiagnosticSessionsApiService {
  private getAuthHeaders(): Record<string, string> {
    const key =
      (import.meta as any).env?.VITE_ADMIN_API_KEY ||
      (typeof localStorage !== 'undefined' ? localStorage.getItem('admin_api_key') : null);

    const headers: Record<string, string> = {};
    if (key) headers['x-admin-key'] = String(key);
    return headers;
  }

  async getSessions(filters: DiagnosticSessionsFilters = {}): Promise<DiagnosticSessionsResponse> {
    const params = new URLSearchParams();
    if (filters.status) params.append('status', filters.status);
    if (filters.search) params.append('search', filters.search);
    if (filters.scoreMin !== undefined) params.append('scoreMin', String(filters.scoreMin));
    if (filters.scoreMax !== undefined) params.append('scoreMax', String(filters.scoreMax));
    if (filters.from) params.append('from', filters.from);
    if (filters.to) params.append('to', filters.to);
    if (filters.page) params.append('page', String(filters.page));
    if (filters.limit) params.append('limit', String(filters.limit));

    const url = `${API_BASE_URL}/diagnostics${params.toString() ? `?${params}` : ''}`;
    const response = await fetch(url, { headers: this.getAuthHeaders() });
    if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);
    return await response.json();
  }

  async setService1Appointment(
    sessionId: string,
    payload: { scheduledAt: string; notes?: string }
  ): Promise<{ success: boolean; data: { appointment: { scheduledAt: string; notes?: string; updatedAt?: string } } }> {
    const response = await fetch(`${API_BASE_URL}/diagnostics/${sessionId}/service1/appointment`, {
      method: 'POST',
      headers: { ...this.getAuthHeaders(), 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(text || `HTTP error! status: ${response.status}`);
    }
    return await response.json();
  }

  async getSession(id: string): Promise<{ success: boolean; data: DiagnosticSession }> {
    const response = await fetch(`${API_BASE_URL}/diagnostics/${id}`, { headers: this.getAuthHeaders() });
    if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);
    return await response.json();
  }

  async getService1Phase5Export(email: string): Promise<{ success: boolean; data: { markdown: string } }> {
    const response = await fetch(
      `${API_BASE_URL}/diagnostic-sessions/service1/phase5/export?email=${encodeURIComponent(email)}`,
      { headers: this.getAuthHeaders() }
    );
    if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);
    return await response.json();
  }

  async uploadService1AuditReport(
    sessionId: string,
    file: File
  ): Promise<{ success: boolean; data: { auditReport: { url: string; fileName?: string; uploadedAt?: string } } }> {
    const form = new FormData();
    form.append('file', file);

    const response = await fetch(`${API_BASE_URL}/diagnostics/${sessionId}/service1/audit-report/upload`, {
      method: 'POST',
      headers: this.getAuthHeaders(),
      body: form,
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(text || `HTTP error! status: ${response.status}`);
    }
    return await response.json();
  }

  async reviewSession(
    id: string,
    payload: {
      orientation_finale: string;
      domaine?: string;
      role?: string;
      decision: 'service1' | 'orientation' | 'echange' | 'no-go';
      notes?: string;
      expertId?: string;
      expertEmail?: string;
    }
  ): Promise<{ success: boolean; data: DiagnosticSession }> {
    const response = await fetch(`${API_BASE_URL}/diagnostics/${id}/review`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...this.getAuthHeaders() },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(text || `HTTP error! status: ${response.status}`);
    }

    return await response.json();
  }

  async deleteSession(id: string): Promise<{ success: boolean; data?: { _id: string } }> {
    const response = await fetch(`${API_BASE_URL}/diagnostics/${id}`, {
      method: 'DELETE',
      headers: this.getAuthHeaders(),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(text || `HTTP error! status: ${response.status}`);
    }

    return await response.json();
  }

  async activateSubscription(id: string): Promise<{ success: boolean; data: DiagnosticSession }> {
    const response = await fetch(`${API_BASE_URL}/diagnostics/${id}/activate-subscription`, {
      method: 'PUT',
      headers: this.getAuthHeaders(),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(text || `HTTP error! status: ${response.status}`);
    }

    return await response.json();
  }

  async updateImplicitStatus(
    id: string,
    implicitStatus: 'en_attente' | 'termine' | 'annule' | 'suspendu'
  ): Promise<{ success: boolean; data: DiagnosticSession }> {
    const response = await fetch(`${API_BASE_URL}/diagnostics/${id}/implicit-status`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...this.getAuthHeaders() },
      body: JSON.stringify({ implicitStatus }),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(text || `HTTP error! status: ${response.status}`);
    }

    return await response.json();
  }
}

export const diagnosticSessionsApiService = new DiagnosticSessionsApiService();
export default diagnosticSessionsApiService;
