import mongoose from 'mongoose';

const diagnosticSessionSchema = new mongoose.Schema(
  {
    status: {
      type: String,
      enum: ['draft', 'submitted', 'reviewed', 'pending', 'validated'],
      default: 'pending',
    },

    subscriptionStatus: {
      type: String,
      enum: ['pending', 'active'],
      default: 'pending',
    },

    participant: {
      fullName: { type: String, trim: true, default: '' },
      firstName: { type: String, trim: true, default: '' },
      email: { type: String, trim: true, lowercase: true, default: '' },
      whatsapp: { type: String, trim: true, default: '' },
      situation: { type: String, trim: true, default: '' },
    },

    responses: {
      type: mongoose.Schema.Types.Mixed,
      required: true,
      default: {},
    },

    scores: {
      perBlock: { type: mongoose.Schema.Types.Mixed, default: {} },
      total: { type: Number, default: 0 },
      orientation: { type: String, default: '' },
    },

    analysis: {
      autoGenerated: { type: Boolean, default: true },
      humanReviewed: { type: Boolean, default: false },
      implicitStatus: {
        type: String,
        enum: ['en_attente', 'termine', 'annule', 'suspendu'],
        default: 'en_attente',
      },
      finalOrientation: { type: String, default: '' },
      domain: { type: String, default: '' },
      recommendedRole: { type: String, default: '' },
      decision: { type: String, default: '' },
      expertId: { type: String, default: '' },
      expertEmail: { type: String, default: '' },
      notes: { type: String, default: '' },
      reviewedAt: { type: Date },
    },

    reviewHistory: {
      type: [
        {
          at: { type: Date, default: Date.now },
          expertId: { type: String, default: '' },
          expertEmail: { type: String, default: '' },
          payload: { type: mongoose.Schema.Types.Mixed, default: {} },
        },
      ],
      default: [],
    },

    metadata: {
      source: { type: String, default: 'web' },
      userAgent: { type: String, default: '' },
      ip: { type: String, default: '' },
      selectedDomain: { type: String, default: '' },
    },

    submittedAt: { type: Date, default: Date.now },
  },
  {
    timestamps: true,
  }
);

// Indexes
// Keep it simple: search by email + most recent first

diagnosticSessionSchema.index({ 'participant.email': 1, submittedAt: -1 });
diagnosticSessionSchema.index({ status: 1, submittedAt: -1 });

export default mongoose.model('DiagnosticSession', diagnosticSessionSchema);
